; PushRelay v0.5 — oleg@abramov.dev

[env:esp32-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = default_8MB.csv
board_build.flash_size = 8MB
board_upload.flash_size = 8MB

lib_deps =
    tzapu/WiFiManager @ ^2.0.17
    ESP32Async/ESPAsyncWebServer @ ^3.6.0
    arkhipenko/TaskScheduler @ ^3.8.5
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.2.0
    h2zero/NimBLE-Arduino @ ^2.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=1
